config/routes.rb
Rails.application.routes.draw do
root "pages#home"

resources :articles
resources :users, except: [:new]

get "about", to: "pages#about"
get "signup", to: "users#new"

get "login", to: "sessions#new"
post "login", to: "sessions#create"
delete "logout", to: "sessions#destroy"

end

app/models/concerns/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true
    validates :description, presence: true
    validates :user_id, presence: true
end

app/models/concerns/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
               uniqueness: {case_sensitive: false},
               length: 3..25
    validates :email, presence: true, 
               uniqueness: {case_sensitive: false},
               format: /@/
    has_secure_password           
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
    flash[:danger] = "You must logged in to perform that action"
    redirect_to root_path
    end
  end
end

app/controllers/concerns/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article_id, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    def home
    end
    
    def index
        @article = Article.all.paginate(page: params[:page], per_page: 6)
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article succesfully created"
            redirect_to article_path(@article)
        else
            render :new
        end
    end
    
    def show
    end
     
    def edit
    end
     
    def update
        @article.user = current_user
        if @article.update(article_params)
            flash[:success] = "Article succesfully updated"
            redirect_to article_path(@article)
        else
            render :edit
        end
    end
     
    def destroy
        @article.destroy
        flash[:danger] = "Article succesfully deleted"
        redirect_to articles_path
    end
     
  
    
    private
    def article_params
        params.require(:article).permit(:title, :description)
    end
    
    def find_article_id
       @article = Article.find(params[:id])  
    end
    
    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit your own article"
            redirect_to root_path
        end
    end
end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
    def home
        @article = Article.all
    end
    
    def about
    end
end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You are successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Your email or your password is incorrect"
            render "new"
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:success]="You have logged out successfully"
        redirect_to root_path
    end

end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    def index
        @user = User.all.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Hola #{@user.username.upcase}, Bienvenido a Prohacktividad!"
            redirect_to user_path(@user)
        else
            render :new
        end
    end
    
    def edit
        
    end
    
    def update
        
        if @user.update(user_params)
            flash[:success] = "Cuenta editada exitosamente"
            redirect_to articles_path
        else
            render :edit
        end
    end
    
    def show
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all articles created by user have been deleted"
        redirect_to users_path
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin user can perform this action"
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_article.html.erb
<div class="container">
  <hr>
  
  <% obj.each do |a| %>
    <div class="jumbotron jumbotron_index">
      <h4 class="display-4"><%= link_to a.title, article_path(a.id) %></h4>
        <p class="lead">
          <%= sanitize a.description[0...150] + "..." %>
          <em><%= a.created_at %></em>|
          <em><%= a.user.username %></em>
        </p> 
        <hr class="my-4">
          
          <%= link_to "Show", article_path(a.id) %> |
          
          <!-- links ONLY FOR ADMIN -->
          <% if logged_in? && (current_user == a.user || current_user.admin?) %>
           <%= link_to "Edit", edit_article_path(a.id) %> |
           <%= link_to "Delete", article_path(a.id), method: :delete, data: {confirm: "Are you sure"} %>
          <%end%>
          <!--THESE LINES DISPLAYED SINCE HOW MANY DAYS THE ARTICLE HAVE BEEN CREATED
            b = Date.today.to_time %>
            (b.to_time.to_i - a.created_at.to_i)/1.day %>
          -->
    </div>
  <% end %>
</div>

app/views/articles/_flash_msg.html.erb
<div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
    
    <div class="alert alert-<%=name%>">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <li><%= msg %></li>
    </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
<%= render "shared/alert", obj: @article %>
<!--Add Bootstrap form Style -->

<div class='row'>
  <div class='col-xs-12'>
    
    <%= form_for(@article, :html =>{class: "form-horizontal", role: "form"}) do |f| %>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Título %>
        </div>
        
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Ingrese el título del artículo", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Descripción %>
        </div>
        
        <div class="col-sm-8">
          <%= f.hidden_field :description, class:"form-control", id: "text_editor", type: "hidden" %>
          <trix-editor style="overflow-y:auto; height: 300px;" input="text_editor" rows="10" class="form-control" placeholder= "Ingrese la descripción del artículo"></trix-editor>
        </div>
        
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
      
      <div class="col-xs-4 col-xs-offset-4">
        [ <%= link_to "Cancelar redacción y volver", articles_path %> ]
      </div>
    
    <% end %>
        
  </div>
</div>

app/views/articles/edit.html.erb
<h3 align="center"><b>Editar Artículo</b></h3>

<%= render 'form' %>

app/views/articles/index.html.erb
<div align="center"> <%= will_paginate @article %> </div>
    <!--< render "articles/article", obj: @article %>-->
    
  <% @article.each do |a| %>  
    <div class="col-6 col-sm-6 col-lg-4">
        <h2 style="text-decoration: underline;"><%= link_to a.title, article_path(a.id)%></h2>
        <em><%= a.created_at%></em>
        <p><%= sanitize a.description[0...150] + "..."%></p>
        <%= link_to "Leer más»", article_path(a.id), class: "btn btn-default" %>
         <% if logged_in? && (current_user == a.user || current_user.admin?) %>
           <%= link_to "Edit", edit_article_path(a.id), class: "btn btn-default" %> |
           <%= link_to "Delete", article_path(a.id), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure"} %>
         <%end%>
    </div>
    <%end%>
<div align="center"> <%= will_paginate @article %> </div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<style>
   body{
       background-color: white;
   }
</style>

<div class="container">
    <div class="col-md-8 col-sm-offset-2 show-article">
        <b> <%= @article.title %></b>
        <h4>Artículo creado el: <%= @article.created_at %></h4>
        <hr>
        <p><%= sanitize @article.description %></p>
    </div>
</div>
<%= link_to "New Article", new_article_path %> |
<%= link_to "Articles", articles_path %>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer>
        </br>
        <div class="row ">
            <div class="col-4 col-sm-4 col-lg-4">
                Copyright &copy; <a href="https://api.whatsapp.com/send?phone=56994924535" target = _blank> TechnoloGeek </a><br>
            </div> 
            
            <div class="col-4 col-sm-4 col-lg-4">
                <a href="https://api.whatsapp.com/send?phone=56994924535" target = _blank> Contactenos al What'sApp </a></br>
            </div> 
            
            <div class="col-4 col-sm-4 col-lg-4">
                <a href="https://www.facebook.com/PlantillasExcelTrucosYtips/" target = _blank> Nuestra Página Facebook </a>
            </div> 
        </div>
    </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo"><b>Pater</b>Blog</a> -->
      <%= link_to image_tag("excel360.png", alt: "ProHacktividad logo"), root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
         <li><%= link_to "Publicaciones", articles_path, id: "links" %></li>
         
         <!--ONLY FOR ADMIN USER-->
         <% if logged_in? %> 
          <li><%= link_to "Crear Artículo", new_article_path, id: "links" %></a></li>
          <li><%= link_to "Usuarios", users_path, id: "links" %></li>
        <%end%>
        
        <li class="dropdown">
            <!-- HERE TO ADD MORE LINKS
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">An action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
            -->
          </ul>
        </li>
      </ul>
      <!-- HERE IS A SEARCH BAR
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
       
        <ul class="nav navbar-nav navbar-right">
         
         <% if logged_in?  %>
          <li><%= link_to "SALIR", logout_path, method: :delete, id: "links" %></li>
          <li class="dropdown">
            <a href="#" id="links" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi Cuenta<%=" Admin" if current_user.admin?%><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar Perfil", edit_user_path(current_user) %></li>
              <li><%= link_to "Ver Perfil", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <li><%= link_to "REGÍSTRATE", signup_path, id: "links" %></li> 
        <li><%= link_to "INICIAR SESIÓN", login_path, id: "links" %></li>
      <% end %>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ExcelHR360</title>
  <%=favicon_link_tag 'favicon1.ico', type: 'image/png'%>
  <link rel="stylesheet" type="text/css" href="trix.css">
  <script type="text/javascript" src="trix.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6651633187654823",
            enable_page_level_ads: true
       });
  </script>
</head>
<body>
  
<%= render 'layouts/navigation' %>  
<%= render 'articles/flash_msg' %>

<div class = container>
  <%= yield %>
</div>

<%= render 'pages/social_media'%>
<% debug(params) if Rails.env.development? %>
<footer>
<%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy 
    eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam 
    voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet 
    clita kasd gubergren, no seaest Lorem ipsum dolor sit amet. Lorem ipsum 
    dolor sit amet, consetetur .
</p>

app/views/pages/home.html.erb
<div class="text-center jumbotron jumbotron_home">
  <div class="container show-case">
    <h1>Hola, Bienvenidos!</h1>
     <div class="container">
      <p class="text-center">
        
          Excel360 es donde puedes resolver tus dudas sobre las funciones de Excel y aprender nuevas funciones.  
          Támbien puedes descargar plantillas gratis para automatizar tus trabajos en Excel.
          <br>
          <hr>
        <h3 style="color:cyan;">Excel360 What'sApp +56 9 9492 4535</h3>
        <em>Tu enciclopedía Excel</em>
      </p>
     </div>
  </div>
  <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>-->
  <%= link_to "Excel Blog", articles_path, class: "btn btn-primary btn-lg" %>
  <%= link_to "Acerca", about_path, class: "btn btn-primary btn-lg" %>
</div>


<!-- SHOW RECENT POST ON HOME PAGE-->
<!--<div class="section-1-header">-->
<!--    <hr>-->
<!--    <h2 class="text-center">Publicaciones recientes</h2>-->
<!--    <hr>-->
<!--</div>-->

<!--    <div class="row"> -->
<!--        <% @article.last(2).each do |a| %>-->
             
<!--            <div class="col-6 col-sm-6 col-lg-6">-->
<!--                <h2><%= link_to a.title, article_path(a.id)%></h2>-->
<!--                <em><%= a.created_at%></em>-->
<!--                <p><%= sanitize a.description[0...150] + "..."%></p>-->
<!--                <%= link_to "Leer más»", article_path(a.id), class: "btn btn-default" %>-->
<!--                 <% if logged_in? && (current_user == a.user || current_user.admin?) %>-->
<!--                   <%= link_to "Edit", edit_article_path(a.id), class: "btn btn-default" %> |-->
<!--                   <%= link_to "Delete", article_path(a.id), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure"} %>-->
<!--                 <%end%>-->
<!--                <hr>-->
<!--            </div>-->
<!--        <% end %>-->
<!--    </div> -->
    



<div class="section-2-header">
  <hr>
  <h2 class="text-center">Plantillas Excel recientes</h2>
  <hr>
</div>

<div class="row text-center">
    <hr>
    <h3 style= "color:#e18604;">CONTROL VACACIONES DE EMPLEADOS EXCEL PLANILLA PROFESSIONAL [2018]</h3>
    <p>¿Necesitas gestionar los <strong>días laborables y festivos de tu empresa</strong>, O eres un <strong>profesional de RR.HH</strong> 
    y siempre tienes problema con las vacaciones de los empleados? Si tu respuesta es <strong>Sí!</strong>, entonces estas en el lugar correcto 
    para resolver tu problema. Este planilla de control de vacaciones en excel no es un simple planilla, pero un
    software completo desarrollado con VBA para ayudarte a tener un buen control de los vacaciones para siempre.
    Es súper eficaz para control de vacaciones de los trabajadores en Excel.</p>
    
    <hr>
    <div class="col-12 col-sm-12 col-lg-12">
        
        <a class ="downloadBtn" href="https://drive.google.com/open?id=1uTLqsS3bgE7D3WZf1gGfSrfk-CVb3zbG" target="_blank">DESCARGAR GRATIS</a>
        <br>

    <!--Carousel part==========================================-->

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
         <%= image_tag("GIF1.gif") %>
      </div>

      <div class="item">
       <%= image_tag("GIF2.gif") %>
      </div>
    
      <div class="item">
        <%= image_tag("GIF3.gif") %>
      </div>
      
      <div class="item">
         <%= image_tag("GIF4.gif") %>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</div>
<!--end Carousel part==========================================-->

<!--================= Remuneraciones=========================-->

<section class="Remun_section">
    <div class="row text-center">
    <hr>
    <h3 style= "color:#e18604;">SISTEMA REMUNERACION / LIQUIDACION DE SUELDO MENSUAL EXCEL [2018]</h3>
    <p>Cálculos Automáticos de descuentos, Impuestos Únicos, Seguro Cesantía etc.<br>
        Ahorra Tiempo, solo ingresar días trabajados y obtener con un click las liquidaciones de sueldo <br>
        Exportar en PDF e imprimir con solo un click <br>
        Libro de remuneraciones y Planilla de pago <br>
    </p>
    <hr>
    
    <a class ="downloadBtn" href="https://drive.google.com/open?id=1HNEfCmcGzcLlZv8MyfTBEnvlilDW0fvF" target="_blank">DESCARGAR GRATIS</a>
    </div>
    
    <div id="myCarousel1" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel1" data-slide-to="1"></li>
      <li data-target="#myCarousel1" data-slide-to="2"></li>
      <li data-target="#myCarousel1" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
         <%= image_tag("renum1.jpg") %>
      </div>

      <div class="item">
       <%= image_tag("renum2.jpg") %>
      </div>
    
      <div class="item">
        <%= image_tag("renum3.jpg") %>
      </div>
      
      <div class="item">
         <%= image_tag("renum4.jpg") %>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel1" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel1" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
</section>
 
</div>   


<br>
<br>
<br>
<br>
<br>
<br>

app/views/shared/_alert.html.erb
<% if obj.errors.any? %>
 <div class="col-sm-8 col-sm-offset-2">
  <div class="alert alert-danger" role="alert">
   <h4>
    <%= pluralize(obj.errors.count, "error")%>
    prohibited this article from being saved:
   </h4>
   <% obj.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
   </div>
 </div> 
<% end %>

app/views/users/_form.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html =>{class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Nombre  %>
        </div>
        
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Ingrese su nombre de usuario", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Email %>
        </div>
        
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Ingrese su email", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Password %>
        </div>
        
        <div class="col-sm-8">
          <%= f.password_field :password, class:"form-control" %>
         
        </div>
        
        <div class="col-sm-offset-2 col-sm-10">
            <br>
          <%= f.submit(@user.new_record? ? "Crear Cuenta" : "Guardar Cambios", class: "btn btn-primary btn-lg") %>
          <%= link_to "Cancelar", articles_path, class: "btn btn-lg btn-default" %>
        </div>
      </div>
      
    <% end %>
        
  </div>
</div>

app/views/users/edit.html.erb
<h3 align="center">Editar Cuenta</h3>
<%= render "shared/alert", obj:@user %>
<%= render "users/form" %>

app/views/users/index.html.erb
<div align="center"><%= will_paginate @user %></div>
<% @user.each do |user| %>
    <div class="user-listing">
        <span class="user-img"><%= link_to gravatar_for(user), user_path(user)%></span> 
        <span class="user-name">
         <%= link_to user.username, user_path(user)%> 
        </span><br>
        <em style="margin-left: 70px;"><%= pluralize(user.articles.count, "articulo")%></em>
        <% if logged_in? && current_user.admin? %>
         | <%= link_to "Delete user", user_path(user), method: :delete, data: {confirm: "Are you sure"} %>
        <%end%>
    </div>   
  
<% end %>
<div align="center"><%= will_paginate @user %></div>

app/views/users/new.html.erb
<%= render "shared/alert", obj:@user %>

<div class='row'>
  <div class='col-xs-12'>
    <h3 align="center">Crear su cuenta</h3>
    <%= form_for(@user, :html =>{class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Nombre  %>
        </div>
        
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Ingrese su nombre de usuario", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Email %>
        </div>
        
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Ingrese su email", autofocus: true %>
        </div>
      </div>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :Password %>
        </div>
        
        <div class="col-sm-8">
          <%= f.password_field :password, class:"form-control" %>
         
        </div>
        
        <div class="col-sm-offset-2 col-sm-10">
            <br>
          <%= f.submit "Crear Cuenta", class: "btn btn-primary btn-lg" %>
          <%= link_to "Cancelar", articles_path, class: "btn btn-lg btn-default" %>
        </div>
      </div>
      
    <% end %>
        
  </div>
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%=@user.username%>'s profile</h1>
    <div class="row">
        <div class="col-md-12  text-center">
            <%= gravatar_for @user, size: 150 %>
        </div>
    </div>
    
    <h4 align="center">Articulo publicado por  <%=@user.username%></h4>
    <hr>
    <%= render "articles/article", obj: @user.articles %>
  
     